# Generated by Django 5.1.6 on 2025-02-24 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='department',
        ),
    ]
